baseURL = "https://e99h2121.github.io/blog-hugo/"
publishDir = "docs"
languageCode = "ja-ja"
title = "e99h2121's New Hugo Site"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "e99h2121"
  description = "Where there is a null, there is no way."
  github = "e99h2121"
  twitter = "e99h2121"
  instagram = "e99h2121"
  tumblr = "e99h2121"
  url = "https://e99h2121.github.io/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  location = "Japan"

  [[params.links]]
    title = "Link"
    href = "https://github.com/e99h2121"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
