baseURL = "https://e99h2121.github.io/blog-hugo/"
publishDir = "docs"
languageCode = "ja-ja"
title = "yamada_n's blog"
theme = "github-style"
googleAnalytics = "G-GDXTY41XGN"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "yamada_n"
  description = "Where there is a null, there is no way."
  github = "e99h2121"
  twitter = "e99h2121"
  instagram = "e99h2121"
  tumblr = "e99h2121"
  url = "https://e99h2121.github.io/"
  keywords = "blog"
  rss = true
  lastmod = true
  location = "Japan"

  [[params.links]]
    title = "Link"
    href = "https://e99h2121.github.io/"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
